services:
  django:
    build: ./app
    env_file:
      - .env.dev
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

    ports:
      - 8000:8000
    depends_on:
      - pgdb
      - redis
      - celery-worker
      - celery-beat

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery-worker:
    build: ./app
    env_file:
      - .env.dev
    command: celery -A WeatherReminder worker -l INFO
    depends_on:
      - redis

  celery-beat:
    build: ./app
    env_file:
      - .env.dev
    command: celery -A WeatherReminder beat -l INFO -S django
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:

